name: flare_dart
description: Vector design and runtime animation.
version: 1.2.3
author: "2Dimensions Team <info@2dimensions.com>"
homepage: https://github.com/2d-inc/Flare-Flutter
environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"
