name: slider
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter:
    path: ../../
  nima: ^1.0.2
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flare/Resizing_House.flr
    - assets/nima/Robot_Kr2.nima
    - assets/nima/Robot_Kr20.png
    - assets/nima/Robot_Kr21.png
    - assets/images/flutter.png
    - assets/images/2DLogo.png
    - assets/images/2.0x/2DLogo.png
    - assets/images/3.0x/2DLogo.png
  fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
      - asset: assets/fonts/Roboto-Bold.ttf
        weight: 700
      - asset: assets/fonts/Roboto-Light.ttf
        weight: 100